### ISSUE TITLE
老哥，我复现不出来这个ManiGAN啊

### ISSUE THREAD

**Issue by zhangqian001** [Collapsar-G/ManiGan#1]
我预训练MASM的时候，程序报错的很多，老哥能教教我么。感激不尽。

**Comment by Collapsar-G** [comment]
我记得是utils文件里面有一个函数调用少参数，你对比一下我的那个文件和原作者的文件，应该改一下就差不多了，最近忙着备战考研  Orz

**Comment by zhangqian001** [comment]
老哥，能加一个微信或者QQ么？我是20考研，现在是研一，说不定能帮上你。我的QQ是2483633765，太感谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Collapsar-G/ManiGan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Collapsar-G/ManiGan] 老哥，我复现不出来这个ManiGAN啊 (#1)





 
我记得是utils文件里面有一个函数调用少参数，你对比一下我的那个文件和原作者的文件，应该改一下就差不多了，最近忙着备战考研  Orz

**Comment by zhangqian001** [comment]
老哥，你就是神，加我一个联系方式吧，求求你了。
